name: Build and run
on: [push]
env:
    PYTHON_VERSION: '3.x'
    GO_VERSION: '1.22.x'
jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - name: Build and unit test
        run: |
            cd java
            ./gradlew clean build
  java-run:
    runs-on: ubuntu-latest
    needs: java-test
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - name: Run application
        run: |
            cd java
            ./gradlew run
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}
      - name: Build and unit test
        run: |
            cd python/src
            python3 -m unittest
  python-run:
    runs-on: ubuntu-latest
    needs: python-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}
      - name: Run application
        run: |
            cd python/src
            python3 -m workspace
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test application
        run: |
            cd go/internal/mypackage/
            go test
  go-run:
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run application
        run: |
            cd go/internal/mypackage/
            go run .